# Custom Language File for Launcher Customizer

[ejs.app]
title = "Terraza Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/MdGhYSRb86"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "TERRAZA STUDIOS TE DA LA BIENVENIDA"
welcomeDescription = "Tu aventura comienza aquí. Explora, conecta y vive un mundo hecho para ti."
welcomeDescCTA = "Una experiencia de Terraza Studios"
