# Custom Language File for Launcher Customizer

[ejs.app]
title = "Terraza Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "https://x.com/TerrazaStudios?t=uIYwZVW1fIs0kB5P7AN2yQ&s=09"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/STbegqSVuz"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENIDOS A TERRAZA STUDIOS"
welcomeDescription = ""
welcomeDescCTA = ""
