name: Build Terraza Launcher

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install dmg-license (macOS only)
        if: runner.os == 'macOS'
        run: npm install dmg-license

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: npm run dist:linux

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: npm run dist:win

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: npm run dist:mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraza-launcher-${{ runner.os }}
          path: dist/*
