name: Build macOS App

on:
  push:            # Se ejecuta en cada push
    branches:
      - master       # O la rama que uses
  workflow_dispatch: # También puedes lanzarlo manualmente

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app for macOS
        run: npm run dist:mac

      - name: Upload .dmg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: dist/*.dmg
